// Ebook Agent Bridge - Integration with DIL Autonomous Ebook Agent
// This bridge provides tools to help users interact conceptually with the ebook agent
// No direct API calls to the agent - only generates instructions and payloads

import { EbookBrief, EbookSessionChecklist, ToolOutput } from '../lib/types'

// Generate full GitHub issue body for ebook production
export function generateEbookIssueBody(brief: EbookBrief): string {
  // Mode constraints for session
  let totalChapters = brief.totalChapters || 1
  if (brief.mode === 'session') {
    if (totalChapters < 3) {
      totalChapters = 3
    }
    if (totalChapters > 4) {
      totalChapters = 4
    }
  }

  const lines = [
    '## Judul Ebook',
    brief.ebookTitle,
    '',
    '## Target Pembaca',
    brief.targetAudience,
    '',
    '## Level Pembaca',
    brief.readingLevel,
    '',
    '## Mode Produksi',
    brief.mode,
    '',
    '## Jumlah Bab',
    totalChapters.toString()
  ]

  if (brief.targetPages) {
    lines.push('', '## Target Halaman')
    lines.push(brief.targetPages.toString())
  }

  if (brief.sessionNumber) {
    lines.push('', '## Nomor Sesi')
    lines.push(brief.sessionNumber.toString())
  }

  lines.push('', '## Brief Konten')
  lines.push(brief.contentBrief)

  if (brief.specialInstructions) {
    lines.push('', '## Aturan Khusus')
    lines.push(brief.specialInstructions)
  }

  lines.push('', '## Preferensi API Provider')
  lines.push(brief.apiPreference || 'auto')

  if (brief.pdfRequired !== undefined) {
    lines.push('', '## PDF diperlukan')
    lines.push(brief.pdfRequired ? 'true' : 'false')
  }

  lines.push('', '## Approval untuk eksekusi')
  lines.push('true')

  return lines.join('\n')
}

// Generate session production checklist
export function generateSessionChecklist(
  sessionNumber: number,
  mode: string,
  chapters: number
): EbookSessionChecklist {
  const checklist: EbookSessionChecklist = {
    sessionNumber,
    mode,
    chapters,
    checklistItems: [
      'Judul ebook sudah final',
      'Target audience jelas dan spesifik',
      'Brief konten lengkap (minimal 200 kata)',
      'Mode sudah dipilih dengan benar',
      'Aturan khusus sudah ditulis (jika ada)',
      'API preference sudah dipilih',
      'Approval sudah diberikan',
      'GitHub Secrets sudah dikonfigurasi dengan API key yang valid',
      'Budget sudah dialokasikan untuk biaya API'
    ],
    warnings: []
  }

  // Add mode-specific warnings
  if (mode === 'session') {
    checklist.warnings.push(
      'Mode session membutuhkan minimal 3 bab',
      `Target ${chapters} bab telah diset`,
      'Cost guard akan aktif - biaya akan di-track',
      'Fallback akan aktif jika API gagal'
    )
  }

  if (mode === 'test') {
    checklist.warnings.push(
      'Mode test hanya 1 bab untuk validasi',
      'Biaya minimal - ideal untuk testing API key',
      'Review report akan menentukan kualitas output'
    )
  }

  if (mode === 'planning') {
    checklist.warnings.push(
      'Mode planning tidak menghasilkan konten ebook',
      'Hanya menghasilkan task_plan.json dan outline.json',
      'Cost minimal - hanya untuk planning'
    )
  }

  return checklist
}

// Format checklist as markdown
export function formatChecklistAsMarkdown(checklist: EbookSessionChecklist): string {
  const lines = [
    `# Production Checklist - Session ${checklist.sessionNumber}`,
    '',
    `**Mode:** ${checklist.mode.toUpperCase()}`,
    `**Target Chapters:** ${checklist.chapters}`,
    '',
    '---',
    '',
    '## Checklist Items',
    ''
  ]

  checklist.checklistItems.forEach((item, i) => {
    lines.push(`${i + 1}. [ ] ${item}`)
  })

  if (checklist.warnings.length > 0) {
    lines.push('', '## Warnings', '')
    checklist.warnings.forEach(w => {
      lines.push(`- **WARNING:** ${w}`)
    })
  }

  lines.push('', '---', '', '*Generated by Campaa AI - Ebook Agent Bridge*')

  return lines.join('\n')
}

// Analyze run report from ebook agent
export function analyzeRunReport(report: {
  status: string
  mode: string
  fallback_used: boolean
  review_status?: string
  review_score?: number
  total_cost_usd?: number
  provider_used?: string
  agents_executed?: string[]
  agents_failed?: string[]
}): {
  verdict: string
  recommendation: string
  issues: string[]
  metrics: Record<string, string | number>
} {
  const issues: string[] = []
  let verdict: string
  let recommendation: string

  const metrics = {
    status: report.status,
    reviewStatus: report.review_status || 'N/A',
    reviewScore: report.review_score || 0,
    fallbackUsed: report.fallback_used ? 'Yes' : 'No',
    totalCost: `$${(report.total_cost_usd || 0).toFixed(4)}`,
    provider: report.provider_used || 'none',
    agentsExecuted: report.agents_executed?.length || 0,
    agentsFailed: report.agents_failed?.length || 0
  }

  // Determine verdict
  if (report.status === 'SUCCESS' && report.review_status === 'PASS' && (report.review_score || 0) >= 90) {
    verdict = 'READY TO PUBLISH'
    recommendation = 'Ebook berkualitas tinggi. Siap untuk dipublikasikan atau dijual.'
  } else if (report.fallback_used) {
    verdict = 'NEEDS REVIEW'
    recommendation = 'Output menggunakan fallback (tanpa AI). Periksa kualitas konten.'
    issues.push('AI tidak aktif - perlu configure API key')
    issues.push('Konten mungkin kurang deep dibanding AI generation')
  } else if (report.review_status === 'REPAIR') {
    verdict = 'NEEDS REPAIR'
    recommendation = 'Output memerlukan perbaikan minor. Periksa ebook_repaired.md.'
    issues.push('Quality score di bawah threshold')
  } else if (report.status === 'FAILED') {
    verdict = 'FAILED'
    recommendation = 'Execution gagal. Cek error logs dan coba ulang.'
    issues.push('Agent execution error')
  } else {
    verdict = 'PARTIAL SUCCESS'
    recommendation = 'Output dihasilkan dengan beberapa issues. Review sebelum publish.'
  }

  return { verdict, recommendation, issues, metrics }
}

// Build repair prompt for failed ebook output
export function buildRepairPrompt(issue: string, mode: string): string {
  return `---
# Repair Prompt untuk DIL Ebook Agent

## Issue yang Ditemukan
${issue}

## Mode Ebook
${mode}

## Instruksi Perbaikan

### 1. Identifikasi Masalah
- Apakah issue dari AI generation atau fallback?
- Apakah structural atau content problem?
- Apakah ada placeholder buruk?

### 2. Perbaikan yang Dibutuhkan

#### Jika ada foreign text:
- Hapus karakter asing (Mandarin, Cyrillic, Arabic, dll)
- Ganti dengan Bahasa Indonesia yang sesuai
- Jangan gunakan placeholder seperti "[konten foreign]"

#### Jika ada heading melompat:
- Turunkan level heading agar urut
- Jangan buat heading placeholder

#### Jika ada lapisan hilang:
- Tambahkan [KONSEP], [ANALOGI], [RUMUS], [CONTOH], [APLIKASI]
- Isi dengan konten yang masuk akal
- Jangan gunakan placeholder

#### Jika ada placeholder buruk:
- Ganti dengan konten Indonesia yang safe
- Contoh: "Bagian ini telah disesuaikan untuk memenuhi standar kualitas"

### 3. Validasi Output
- Tidak ada foreign text
- Tidak ada secret leak (API key, token)
- Semua lapisan [KONSEP]-[APLIKASI] ada
- Bahasa Indonesia konsisten
- Heading tidak melompat

### 4. Output
- Simpan ke ebook_repaired.md
- Buat repair_log.json
- Update review_report.json

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
}

// Generate RAW BRIEF for complex ebook production
export function generateRawBrief(input: {
  title: string
  audience: string
  goal: string
  scope: string
  uniqueAngle: string
  targetLength: string
}): string {
  return `---
# RAW BRIEF - Ebook Production

## Basic Info
- **Judul:** ${input.title}
- **Target Audience:** ${input.audience}
- **Goal:** ${input.goal}
- **Scope:** ${input.scope}

## Unique Angle
${input.uniqueAngle}

## Target Length
${input.targetLength}

## Production Instructions

### Target Format
- Format: PDF A4, EPUB
- Bahasa: Indonesia
- Gaya: Profesional tapi friendly
- Tone: Edukatif dengan contoh nyata

### 5-Layer Method (per subbab)
1. [KONSEP] - Penjelasan teori
2. [ANALOGI] - Perumpamaan sederhana
3. [RUMUS] - Prinsip/framework
4. [CONTOH] - Case study
5. [APLIKASI] - Implementasi

### Chapters Structure
1. Fondasi dan context
2. Core concepts (2-3 bab)
3. Advanced strategies
4. Action plan / implementation

### Production Notes
- Setiap bab 1500-2000 kata
- Setiap subbab 300-500 kata
- Total target 5000-8000 kata (session)
- Review score minimal 85

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
}