// Ebook Agent Tool - Integration with DIL Autonomous Ebook Agent
import { ToolOutput, EbookBrief, EbookSessionChecklist } from '../lib/types'

// Generate GitHub Issue body for ebook production
export async function ebookAgentTool(input: {
  action: 'generate_issue_body' | 'generate_checklist' | 'analyze_artifact' | 'build_repair_prompt' | 'session_template'
  brief?: EbookBrief
  artifactPath?: string
  sessionNumber?: number
  context?: Record<string, any>
}): Promise<ToolOutput> {
  try {
    const { action, brief, artifactPath, sessionNumber = 1, context = {} } = input

    let result: string

    switch (action) {
      case 'generate_issue_body': {
        if (!brief) {
          return { success: false, result: 'Ebook brief diperlukan untuk generate issue body', toolUsed: 'ebook_agent' }
        }

        // Validate mode constraints
        let totalChapters = brief.totalChapters || 1
        if (brief.mode === 'session' && totalChapters < 3) {
          totalChapters = 3
        }
        if (brief.mode === 'session' && totalChapters > 4) {
          totalChapters = 4
        }

        result = `---
# Ebook Generation Request

## Judul Ebook
${brief.ebookTitle}

## Target Pembaca
${brief.targetAudience}

## Level Pembaca
${brief.readingLevel}

## Mode Produksi
${brief.mode}

## Jumlah Bab
${totalChapters}

${brief.targetPages ? `## Target Halaman\n${brief.targetPages}` : ''}

${brief.sessionNumber ? `## Nomor Sesi\n${brief.sessionNumber}` : ''}

## Brief Konten
${brief.contentBrief}

${brief.specialInstructions ? `## Aturan Khusus\n${brief.specialInstructions}` : ''}

## Preferensi API Provider
${brief.apiPreference || 'auto'}

${brief.pdfRequired !== undefined ? `## PDF diperlukan\n${brief.pdfRequired ? 'true' : 'false'}` : ''}

## Approval untuk eksekusi
true

---

## Checklist Sebelum Submit

- [x] Judul ebook sudah jelas dan spesifik
- [x] Target pembaca sudah teridentifikasi
- [x] Level pembaca sesuai dengan konten
- [x] Brief konten cukup detail
- [x] Mode yang dipilih sudah tepat
- [x] Approval sudah diberikan

## Catatan

- Mode test: 1 bab pendek untuk validasi (biaya minimal)
- Mode session: ${totalChapters} bab untuk satu sesi produksi
- Semua API memiliki kuota dan biaya masing-masing
- Tidak ada klaim gratis tanpa limit

---
*Generated by Campaa AI - Ebook Agent Bridge*
*Copy body ini ke GitHub Issue untuk memicu agent otonom*
`
        break
      }

      case 'generate_checklist': {
        const mode = context.mode || 'session'
        const chapters = context.chapters || 3

        const checklist: EbookSessionChecklist = {
          sessionNumber,
          mode,
          chapters,
          checklistItems: [
            'Judul ebook sudah final dan marketable',
            'Target audience sudah jelas dan spesifik',
            'Brief konten sudah lengkap dan detail',
            'Aturan khusus sudah ditulis (jika ada)',
            'API provider preference sudah dipilih',
            'Approval sudah diberikan',
            'Budget sudah dianggarkan (biaya API)',
            'GitHub Secrets sudah dikonfigurasi dengan API key'
          ],
          warnings: [
            mode === 'session' ? 'Minimal 3 bab diperlukan untuk mode session' : '',
            'Mode full memerlukan approval eksplisit',
            'Cost guard aktif - akan fallback jika budget exceeded',
            'Review report akan menentukan apakah output layak publish'
          ].filter(Boolean)
        }

        result = `---
# Session ${sessionNumber} Production Checklist

## Mode: ${mode.toUpperCase()}
## Target Chapters: ${chapters}

## Checklist Items

${checklist.checklistItems.map((item, i) => `${i + 1}. [ ] ${item}`).join('\n')}

## Warnings

${checklist.warnings.map(w => `- **Warning:** ${w}`).join('\n')}

## Expected Output

| File | Description |
|------|-------------|
| ebook.md | Konten ebook final |
| task_plan.json | Rencana task |
| outline.json | Outline ebook |
| run_report.json | Laporan eksekusi |
| cost_report.json | Laporan biaya |
| review_report.json | Quality review |

## Risk Assessment

- **API failure**: Fallback template aktif - output tetap dihasilkan
- **Budget exceeded**: Cost guard menahan request
- **Low quality**: Reviewer agent mendeteksi dan repair agent bisa memperbaiki
- **Secret leak**: Safety validator menolak output

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
        break
      }

      case 'analyze_artifact': {
        // Analyze output from DIL Autonomous Ebook Agent
        const report = context.reportData || {}
        const status = report.status || 'unknown'
        const reviewStatus = report.review_status || 'unknown'
        const reviewScore = report.review_score || 0
        const fallbackUsed = report.fallback_used || false
        const totalCost = report.total_cost_usd || 0

        result = `---
# Artifact Analysis

## Execution Status

| Metric | Value |
|--------|-------|
| Status | ${status.toUpperCase()} |
| Review | ${reviewStatus} (score: ${reviewScore}/100) |
| Fallback Used | ${fallbackUsed ? 'Yes - API tidak tersedia' : 'No - AI aktif'} |
| Total Cost | $${totalCost.toFixed(4)} |

## Assessment

`

        if (status === 'SUCCESS' && reviewStatus === 'PASS' && reviewScore >= 90) {
          result += `### Verdict: READY TO PUBLISH

Ebook berkualitas tinggi dan siap dipublikasikan.
- Review score: ${reviewScore}/100
- AI generation aktif
- Quality standards met`

        } else if (status === 'PARTIAL_SUCCESS' && fallbackUsed) {
          result += `### Verdict: NEEDS REVIEW

Output dihasilkan menggunakan fallback (tanpa AI).
- AI generation tidak aktif
- Review score: ${reviewScore}/100
- Perlu dicek apakah konten fallback memenuhi standar

**Recommendations:**
1. Aktifkan API key di GitHub Secrets
2. Jalankan ulang di mode yang sama
3. Verifikasi output sebelum publish`

        } else if (reviewStatus === 'REPAIR') {
          result += `### Verdict: NEEDS REPAIR

Output memerlukan perbaikan minor.
- Review score: ${reviewScore}/100
- Repair agent sudah dijalankan
- Periksa ebook_repaired.md

**Actions:**
1. Review ebook_repaired.md
2. Jika masih ada issue, repair manual
3. Verifikasi sebelum publish`

        } else {
          result += `### Verdict: MANUAL INTERVENTION REQUIRED

Output tidak memenuhi standar minimum.
- Status: ${status}
- Review: ${reviewStatus}
- Score: ${reviewScore}/100

**Actions:**
1. Cek error_log.txt untuk error details
2. Perbaiki masalah yang teridentifikasi
3. Jalankan ulang jika perlu`

        }

        result += `

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
        break
      }

      case 'build_repair_prompt': {
        const issue = context.issue || 'Kualitas output rendah'
        const mode = context.mode || 'general'

        result = `---
# Repair Prompt untuk Ebook Agent

## Issue yang Ditemukan
${issue}

## Mode Ebook
${mode}

## Instruksi Repair

1. **Identifikasi Root Cause**
   - Apakah issue dari AI generation atau dari fallback?
   - Apakah masalah structural atau content?

2. **Perbaikan yang Dibutuhkan**
   - Perbaiki konten yang bermasalah
   - Jangan gunakan placeholder seperti "[konten foreign]" atau "Section placeholder"
   - Pastikan semua lapisan [KONSEP], [ANALOGI], [RUMUS], [CONTOH], [APLIKASI] ada

3. **Validasi**
   - Pastikan tidak ada teks asing (Mandarin, Cyrillic, Arabic, dll)
   - Pastikan tidak ada secret atau API key
   - Pastikan Bahasa Indonesia konsisten dan rapi
   - Pastikan heading tidak melompat

4. **Output**
   - Simpan hasil perbaikan ke ebook_repaired.md
   - Log setiap perbaikan yang dilakukan
   - Buat repair_summary.json

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
        break
      }

      case 'session_template': {
        const mode = context.mode || 'session'
        const chapters = context.chapters || 3

        result = `---
# Session Template untuk Ebook Production

## Mode: ${mode.toUpperCase()}
## Target: ${chapters} chapters

## Session Structure

### Session 1: Planning & Foundation
- Buat task plan
- Buat outline dengan ${chapters} bab
- Review outline bersama
- Approve outline

### Session 2: Production (Bab 1-${Math.ceil(chapters / 2)})
- Generate Bab 1 dan Bab 2
- Review setiap bab
- Repair jika perlu
- Simpan intermediate output

### Session ${mode === 'full' ? '3-4' : '3'}: Completion
- Generate Bab ${Math.ceil(chapters / 2) + 1}${chapters > 2 ? ` dan Bab ${chapters}` : ''}
- Final review
- Aggregasi cost report
- Finalisasi ebook.md

## 5-Layer Method per Subsection

Setiap subbab harus punya:

1. **[KONSEP]** - Penjelasan teori dan konsep
2. **[ANALOGI]** - Perumpamaan dari kehidupan sehari-hari
3. **[RUMUS]** - Prinsip atau framework
4. **[CONTOH]** - Case study atau studi kasus
5. **[APLIKASI]** - Implementasi praktis

## Cost Guard Settings

| Mode | Max Tokens | Max Cost | Bab Target |
|------|------------|----------|------------|
| planning | 10,000 | $0.05 | 0 |
| test | 25,000 | $0.10 | 1 |
| session | 100,000 | $0.50 | 3-4 |
| full | 500,000 | $2.00 | 5-10 |

## Quality Gates

1. Reviewer score >= 80 untuk PASS
2. Tidak ada foreign text
3. Tidak ada secret leak
4. Semua lapisan ada
5. Bahasa Indonesia konsisten

---
*Generated by Campaa AI - Ebook Agent Bridge*
`
        break
      }

      default:
        return { success: false, result: 'Action tidak dikenal', toolUsed: 'ebook_agent' }
    }

    return {
      success: true,
      result,
      toolUsed: 'ebook_agent',
      metadata: { action, sessionNumber }
    }
  } catch (error) {
    return { success: false, result: `Ebook agent tool error: ${error}`, toolUsed: 'ebook_agent' }
  }
}