// Markdown Export Tool - Convert chat to structured documents
import { ToolOutput, AIMessage } from '../lib/types'

export async function markdownExportTool(input: {
  messages: AIMessage[]
  format: 'markdown' | 'txt' | 'json' | 'issue_body'
  title?: string
  includeMetadata?: boolean
}): Promise<ToolOutput> {
  try {
    const { messages, format, title = 'Chat Export', includeMetadata = true } = input

    if (!messages || messages.length === 0) {
      return { success: false, result: 'Tidak ada pesan untuk di-export', toolUsed: 'markdown_export' }
    }

    let result: string

    switch (format) {
      case 'markdown': {
        const lines: string[] = [
          `# ${title}`,
          '',
          `> Ekspor dari Campaa AI - ${new Date().toLocaleString('id-ID')}`,
          ''
        ]

        if (includeMetadata) {
          lines.push(`**Total Pesan:** ${messages.length}`)
          lines.push(`**Durasi:** ${formatDuration(messages)}`)
          lines.push('')
          lines.push('---')
          lines.push('')
        }

        for (const msg of messages) {
          const role = msg.role === 'user' ? 'Anda' : msg.role === 'assistant' ? 'Campaa AI' : 'System'
          const time = new Date(msg.timestamp).toLocaleString('id-ID')
          lines.push(`### ${role} — ${time}`)
          lines.push('')
          lines.push(msg.content)
          lines.push('')
          lines.push('---')
          lines.push('')
        }

        lines.push(`*Generated by Campaa AI*`)
        result = lines.join('\n')
        break
      }

      case 'txt': {
        const lines: string[] = [
          title,
          '='.repeat(title.length),
          `Ekspor: ${new Date().toLocaleString('id-ID')}`,
          `Total pesan: ${messages.length}`,
          '',
          ''
        ]

        for (const msg of messages) {
          const role = msg.role === 'user' ? '[USER]' : msg.role === 'assistant' ? '[AI]' : '[SYSTEM]'
          const time = new Date(msg.timestamp).toLocaleTimeString('id-ID')
          lines.push(`${role} ${time}`)
          lines.push(msg.content)
          lines.push('')
          lines.push('-'.repeat(50))
          lines.push('')
        }

        result = lines.join('\n')
        break
      }

      case 'json': {
        const data = {
          title,
          exportedAt: new Date().toISOString(),
          totalMessages: messages.length,
          messages: messages.map(m => ({
            role: m.role,
            content: m.content,
            timestamp: new Date(m.timestamp).toISOString(),
            mode: m.mode,
            provider: m.provider
          }))
        }
        result = JSON.stringify(data, null, 2)
        break
      }

      case 'issue_body': {
        // Format for GitHub issue - ebook agent integration
        const userMessages = messages.filter(m => m.role === 'user')
        const lastMessage = userMessages[userMessages.length - 1]
        result = lastMessage ? lastMessage.content : messages[0].content
        break
      }

      default:
        return { success: false, result: 'Format tidak dikenal', toolUsed: 'markdown_export' }
    }

    return {
      success: true,
      result,
      toolUsed: 'markdown_export',
      metadata: { format, messageCount: messages.length }
    }
  } catch (error) {
    return { success: false, result: `Export error: ${error}`, toolUsed: 'markdown_export' }
  }
}

function formatDuration(messages: AIMessage[]): string {
  if (messages.length < 2) return 'Singkat'
  
  const first = messages[0].timestamp
  const last = messages[messages.length - 1].timestamp
  const diffMs = last - first
  const diffMinutes = Math.floor(diffMs / 60000)
  
  if (diffMinutes < 1) return 'Kurang dari 1 menit'
  if (diffMinutes < 60) return `${diffMinutes} menit`
  
  const hours = Math.floor(diffMinutes / 60)
  const mins = diffMinutes % 60
  return `${hours} jam ${mins} menit`
}

// Download helper
export function downloadExport(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}