// Repository Helper Tool - Create GitHub artifacts
import { ToolOutput } from '../lib/types'

export type RepositoryArtifactType = 
  | 'readme' 
  | 'issue_template' 
  | 'commit_message' 
  | 'workflow_yaml'
  | 'folder_structure'
  | 'gitignore'

export async function repositoryHelperTool(input: {
  type: RepositoryArtifactType
  projectName?: string
  description?: string
  context?: Record<string, any>
}): Promise<ToolOutput> {
  try {
    const { type, projectName = 'Project', description = '', context = {} } = input

    let result = ''
    const name = projectName.toLowerCase()
    const scope = context.scope || ''
    const scopePrefix = scope ? '(' + scope + ')' : ''

    switch (type) {
      case 'readme': {
        result = [
          '---',
          '# ' + projectName,
          description || 'Project description here',
          '',
          '## Features',
          '- Feature 1',
          '- Feature 2',
          '- Feature 3',
          '',
          '## Installation',
          '```bash',
          '# Clone the repository',
          'git clone https://github.com/username/' + name + '.git',
          '# Navigate to project',
          'cd ' + name,
          '# Install dependencies',
          'npm install',
          '# Run development server',
          'npm run dev',
          '```',
          '',
          '## Usage',
          '```bash',
          '# Build for production',
          'npm run build',
          '# Preview production build',
          'npm run preview',
          '```',
          '',
          '## Documentation',
          'See docs/ for detailed documentation.',
          '',
          '## Contributing',
          '1. Fork the project',
          '2. Create your feature branch',
          '   git checkout -b feature/AmazingFeature',
          '3. Commit your changes',
          "   git commit -m 'Add some AmazingFeature'",
          '4. Push to the branch',
          '   git push origin feature/AmazingFeature',
          '5. Open a Pull Request',
          '',
          '## License',
          'This project is licensed under the MIT License.',
          '',
          '---',
          '*Generated by Campaa AI - Repository Helper Tool*'
        ].join('\n')
        break
      }

      case 'issue_template': {
        result = [
          '---',
          'name: Bug Report',
          'description: Laporkan bug atau masalah',
          'labels: [bug]',
          'title: "[Bug] "',
          '',
          'body:',
          '',
          '- type: markdown',
          '  attributes:',
          '    value: |',
          '      ## Deskripsi Bug',
          '      Jelaskan bug yang ditemukan secara detail.',
          '',
          '- type: textarea',
          '  id: steps',
          '  attributes:',
          '    label: Langkah Reproduksi',
          '    description: Langkah-langkah untuk mereproduksi bug',
          '    placeholder: |',
          '      1. Go to...',
          '      2. Click on...',
          '      3. See error',
          '  validations:',
          '    required: true',
          '',
          '- type: textarea',
          '  id: expected',
          '  attributes:',
          '    label: Perilaku yang Diharapkan',
          '  validations:',
          '    required: true',
          '',
          '- type: textarea',
          '  id: actual',
          '  attributes:',
          '    label: Perilaku Sebenarnya',
          '  validations:',
          '    required: true',
          '',
          '- type: dropdown',
          '  id: os',
          '  attributes:',
          '    label: Operating System',
          '  options:',
          '    - Windows',
          '    - macOS',
          '    - Linux',
          '    - Other',
          '',
          '- type: textarea',
          '  id: context',
          '  attributes:',
          '    label: Additional Context',
          '    description: Informasi tambahan',
          '',
          '---',
          '',
          '*Generated by Campaa AI - Repository Helper Tool*'
        ].join('\n')
        break
      }

      case 'commit_message': {
        result = [
          '---',
          '# Commit Message Convention',
          '',
          '## Format',
          '```',
          '<type>' + scopePrefix + ': <description>',
          '',
          '[optional body]',
          '',
          '[optional footer]',
          '```',
          '',
          '## Types',
          '',
          '| Type | Description |',
          '|------|-------------|',
          '| feat | Feature baru |',
          '| fix | Bug fix |',
          '| docs | Dokumentasi |',
          '| style | Formatting |',
          '| refactor | Code restructure |',
          '| test | Testing |',
          '| chore | Maintenance |',
          '',
          '## Examples',
          '',
          '```',
          'feat: add user authentication',
          'fix(auth): resolve login redirect issue',
          'docs: update README',
          'refactor(api): extract handler',
          'chore: upgrade dependencies',
          '```',
          '',
          '## Rules',
          '1. Use imperative mood',
          '2. Keep first line under 72 characters',
          '3. Use body for explanation',
          '4. Reference issues in footer',
          '',
          '---',
          '*Generated by Campaa AI - Repository Helper Tool*'
        ].join('\n')
        break
      }

      case 'workflow_yaml': {
        result = [
          '---',
          'name: CI/CD Pipeline',
          '',
          'on:',
          '  push:',
          '    branches: [main]',
          '  pull_request:',
          '    branches: [main]',
          '',
          'jobs:',
          '  build:',
          '    runs-on: ubuntu-latest',
          '    steps:',
          '      - name: Checkout code',
          '        uses: actions/checkout@v4',
          '',
          '      - name: Setup Node.js',
          '        uses: actions/setup-node@v4',
          '        with:',
          "          node-version: '20'",
          "          cache: 'npm'",
          '',
          '      - name: Install dependencies',
          '        run: npm ci',
          '',
          '      - name: Type check',
          '        run: npm run typecheck',
          '',
          '      - name: Build',
          '        run: npm run build',
          '',
          '      - name: Test',
          '        run: npm test',
          '',
          '      - name: Upload artifacts',
          '        uses: actions/upload-artifact@v4',
          '        with:',
          '          name: build-output',
          '          path: dist/',
          '',
          '---',
          '*Generated by Campaa AI - Repository Helper Tool*'
        ].join('\n')
        break
      }

      case 'folder_structure': {
        result = [
          '---',
          '# Folder Structure',
          '',
          '## Frontend (React/Vite)',
          '```',
          'project/',
          '├── public/',
          '│   └── favicon.svg',
          '├── src/',
          '│   ├── components/',
          '│   ├── pages/',
          '│   ├── lib/',
          '│   ├── hooks/',
          '│   ├── styles/',
          '│   ├── App.tsx',
          '│   └── main.tsx',
          '├── docs/',
          '├── tests/',
          '├── package.json',
          '├── vite.config.ts',
          '└── tsconfig.json',
          '```',
          '',
          '## Backend (Node.js)',
          '```',
          'server/',
          '├── src/',
          '│   ├── routes/',
          '│   ├── controllers/',
          '│   ├── services/',
          '│   ├── models/',
          '│   └── index.ts',
          '├── tests/',
          '└── package.json',
          '```',
          '',
          '## Key Principles',
          '1. Separation of concerns',
          '2. Feature-based grouping',
          '3. Flat structure (max 3 levels)',
          '4. Use barrel exports (index.ts)',
          '',
          '---',
          '*Generated by Campaa AI - Repository Helper Tool*'
        ].join('\n')
        break
      }

      case 'gitignore': {
        result = [
          '# Dependencies',
          'node_modules/',
          '',
          '# Build outputs',
          'dist/',
          'build/',
          '',
          '# Environment variables',
          '.env',
          '.env.local',
          '.env.production',
          '.env.*.local',
          '',
          '# IDE',
          '.vscode/',
          '.idea/',
          '*.swp',
          '',
          '# OS',
          '.DS_Store',
          'Thumbs.db',
          '',
          '# Logs',
          '*.log',
          'npm-debug.log*',
          '',
          '# Vercel / Netlify',
          '.vercel/',
          '.netlify/',
          '',
          '# Testing',
          'coverage/',
          '',
          '# TypeScript',
          '*.tsbuildinfo',
          '',
          '# Misc',
          '*.bak',
          '*.tmp'
        ].join('\n')
        break
      }

      default:
        return { success: false, result: 'Artifact type tidak dikenal', toolUsed: 'repository_helper' }
    }

    return {
      success: true,
      result,
      toolUsed: 'repository_helper',
      metadata: { type, projectName }
    }
  } catch (error) {
    return { success: false, result: 'Repository helper error: ' + error, toolUsed: 'repository_helper' }
  }
}