// Task Planner Tool - Break down complex requests into steps
import { ToolOutput } from '../lib/types'

export interface TaskStep {
  order: number
  task: string
  description: string
  estimatedTime?: string
  risk?: string
  validation?: string
}

export async function taskPlannerTool(input: {
  query: string
  mode?: 'simple' | 'medium' | 'complex'
  context?: Record<string, any>
}): Promise<ToolOutput> {
  try {
    const { query, mode = 'medium', context = {} } = input

    // Simple task decomposition
    const steps: TaskStep[] = []
    let stepNum = 1

    // Step 1: Clarify goal
    steps.push({
      order: stepNum++,
      task: 'Klarifikasi Tujuan',
      description: 'Pahami dengan jelas: ' + query,
      estimatedTime: '2-5 menit',
      risk: 'Tidak ada',
      validation: 'Tujuan sudah jelas dan spesifik'
    })

    // Step 2: Decompose
    steps.push({
      order: stepNum++,
      task: 'Pecah menjadi Sub-tugas',
      description: 'Identifikasi 3-5 komponen utama dari tugas ini',
      estimatedTime: '5-10 menit',
      risk: 'Low',
      validation: 'Setiap sub-tugas sudah terdefinisi'
    })

    // Step 3: Research/Plan
    if (mode !== 'simple') {
      steps.push({
        order: stepNum++,
        task: 'Riset atau Perencanaan',
        description: mode === 'complex' 
          ? 'Lakukan riset mendalam, validasi asumsi, dan buat rencana detail'
          : 'Riset ringan untuk memahami konteks',
        estimatedTime: mode === 'complex' ? '30-60 menit' : '10-20 menit',
        risk: 'Medium - mungkin butuh iterasi',
        validation: 'Rencana sudah lengkap dan realistis'
      })
    }

    // Step 4: Execute
    steps.push({
      order: stepNum++,
      task: 'Eksekusi',
      description: mode === 'complex'
        ? 'Jalankan setiap sub-tugas dengan validasi berkala'
        : 'Kerjakan tugas utama secara langsung',
      estimatedTime: mode === 'complex' ? '1-4 jam' : '20-60 menit',
      risk: mode === 'complex' ? 'Medium - bisa ada blocker' : 'Low',
      validation: 'Output substansial sudah dihasilkan'
    })

    // Step 5: Review
    steps.push({
      order: stepNum++,
      task: 'Review dan Refinement',
      description: 'Periksa hasil, identifikasi gap, dan perbaiki',
      estimatedTime: '10-30 menit',
      risk: 'Low',
      validation: 'Hasil sudah memenuhi standar kualitas'
    })

    // Step 6: Finalize
    steps.push({
      order: stepNum++,
      task: 'Finalisasi dan Deliver',
      description: 'Susun output final, dokumentasi, dan handover',
      estimatedTime: '10-20 menit',
      risk: 'None',
      validation: 'Output siap delivered'
    })

    // Build markdown output
    const complexityLabel = mode === 'simple' ? 'Simple - 2-4 jam' : mode === 'medium' ? 'Medium - 4-8 jam' : 'Complex - 8+ jam'

    let result = '---' + '\n'
    result += '# Task Plan: ' + query.slice(0, 100) + (query.length > 100 ? '...' : '') + '\n\n'
    result += '## Complexity Level\n' + complexityLabel + '\n\n'
    result += '## Overview\n'
    result += 'Tugas ini dipecah menjadi **' + steps.length + '** langkah yang bisa dijalankan secara berurutan.\n\n'
    result += '---\n\n'
    result += '## Langkah-Langkah\n\n'

    for (const step of steps) {
      result += '### ' + step.order + '. ' + step.task + '\n'
      result += '**Estimasi:** ' + (step.estimatedTime || 'Tidak diketahui')
      if (step.risk) result += '\n**Risiko:** ' + step.risk
      result += '\n\n' + step.description + '\n'
      result += '\n**Validasi:** ' + (step.validation || 'Tidak ada criteria') + '\n\n'
      result += '---\n\n'
    }

    result += '## Tips Eksekusi\n'
    result += '- Mulai dari langkah 1 dan jangan skip\n'
    result += '- Validasi setiap langkah sebelum lanjut ke berikutnya\n'
    result += '- Jika ada blocker, ulangi langkah sebelumnya dengan informasi baru\n'
    result += '- Dokumentasikan setiap keputusan penting\n\n'
    result += '## Warning\n'
    result += '- Jangan mulai dari langkah akhir - setiap langkah membangun di atas sebelumnya\n'
    result += '- Jika tugas terasa terlalu besar, pecah lagi menjadi sub-tugas yang lebih kecil\n\n'
    result += '---\n'
    result += '*Generated by Campaa AI - Task Planner Tool*\n'

    return {
      success: true,
      result,
      toolUsed: 'task_planner',
      metadata: { 
        stepCount: steps.length, 
        mode, 
        query: query.slice(0, 100) 
      }
    }
  } catch (error) {
    return { success: false, result: 'Task planner error: ' + error, toolUsed: 'task_planner' }
  }
}