// Tool Registry - Central registry of all available tools
import { ToolDefinition, ToolType } from '../lib/types'

export const TOOL_REGISTRY: Record<ToolType, ToolDefinition> = {
  calculator: {
    id: 'calculator',
    name: 'Calculator',
    description: 'Perhitungan matematika dan estimasi biaya AI',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { calculatorTool } = await import('./calculatorTool')
      return calculatorTool(input)
    }
  },

  prompt: {
    id: 'prompt',
    name: 'Prompt Enhancer',
    description: 'Ubah input menjadi prompt terstruktur untuk riset, ebook, coding, audit, atau bisnis',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { promptTool } = await import('./promptTool')
      return promptTool(input)
    }
  },

  markdown_export: {
    id: 'markdown_export',
    name: 'Markdown Export',
    description: 'Export percakapan sebagai Markdown, TXT, atau JSON',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { markdownExportTool } = await import('./markdownExportTool')
      return markdownExportTool(input)
    }
  },

  task_planner: {
    id: 'task_planner',
    name: 'Task Planner',
    description: 'Pecah tugas kompleks menjadi langkah-langkah terstruktur',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { taskPlannerTool } = await import('./taskPlannerTool')
      return taskPlannerTool(input)
    }
  },

  repository_helper: {
    id: 'repository_helper',
    name: 'Repository Helper',
    description: 'Generate README, issue template, commit message, atau workflow YAML',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { repositoryHelperTool } = await import('./repositoryHelperTool')
      return repositoryHelperTool(input)
    }
  },

  ebook_agent: {
    id: 'ebook_agent',
    name: 'Ebook Agent Bridge',
    description: 'Generate GitHub issue body, checklist, atau analyze artifact dari DIL Ebook Agent',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const { ebookAgentTool } = await import('./ebookAgentTool')
      return ebookAgentTool(input)
    }
  },

  safety_check: {
    id: 'safety_check',
    name: 'Safety Checker',
    description: 'Periksa input/output untuk risiko keamanan API key, token, atau data sensitif',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const result = checkSafety(input.query || input.text || '')
      return {
        success: true,
        result,
        toolUsed: 'safety_check',
        metadata: {}
      }
    }
  },

  reasoning: {
    id: 'reasoning',
    name: 'Reasoning Engine',
    description: 'Pemecahan masalah kompleks secara step-by-step',
    requiresApproval: false,
    riskLevel: 'safe',
    execute: async (input: any) => {
      const result = reasonThrough(input.query || input.problem || '')
      return {
        success: true,
        result,
        toolUsed: 'reasoning',
        metadata: {}
      }
    }
  }
}

function checkSafety(text: string): string {
  const secrets = [
    /sk-[a-zA-Z0-9]{20,}/,
    /ghp_[a-zA-Z0-9]{36,}/,
    /AIza[a-zA-Z0-9_-]{35,}/,
    /password["\']?\s*[:=]\s*["\']?[^\s"']{8,}/i
  ]

  const issues: string[] = []
  
  for (const pattern of secrets) {
    if (pattern.test(text)) {
      issues.push('Potentially sensitive data detected - will be sanitized')
    }
  }

  if (issues.length > 0) {
    return `Safety Check: ISSUES FOUND\n\n${issues.join('\n')}\n\nAction: Data akan disensor sebelum diproses.`
  }

  return 'Safety Check: CLEAN\n\nTidak ada data sensitif terdeteksi. Aman untuk diproses.'
}

function reasonThrough(problem: string): string {
  return `---
# Reasoning: ${problem.slice(0, 100)}${problem.length > 100 ? '...' : ''}

## Step 1: Clarifikasi Tujuan
Apa yang sebenarnya ingin dicapai dari masalah ini?

## Step 2: Identifikasi Komponen
Daftar elemen-elemen utama yang terlibat.

## Step 3: Identifikasi Constraint
Batasan waktu, budget, teknologi, atau sumber daya.

## Step 4: Options Analysis
Opsi-opsi yang tersedia dengan pros/cons masing-masing.

## Step 5: Risk Assessment
Risiko utama dan mitigation untuk masing-masing opsi.

## Step 6: Recommendation
Saran keputusan dengan reasoning yang jelas.

## Step 7: Action Plan
Langkah konkret yang bisa diambil sekarang.

---
*Generated by Campaa AI - Reasoning Engine*
`
}

export function getTool(toolId: ToolType): ToolDefinition | undefined {
  return TOOL_REGISTRY[toolId]
}

export function getAllTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY)
}

export function getToolsByCategory(category: 'safe' | 'approval_required' | 'blocked'): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter(t => t.riskLevel === category)
}